run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  show-stats: true
  sort-results: true
  sort-order:
    - severity
    - linter
    - file

linters:
  disable-all: true
  enable:
    - gci
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
  # - unused
    - goheader
    - whitespace
  # presets:
  #   - bugs
  #   - comment
  #   - import

issues:
  exclude:
    - G101 # gosec: Potential hardcoded credentials
  max-same-issues: 0
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # exclude ineffassing linter for generated files for conversion
    - linters:
        - dogsled
      text: "declaration has 3 blank identifiers"
      path: _test\.go
    - linters:
        - dupl
      path: _test\.go
    - linters:
        - goheader
      source: "^//go:build"
    - linters:
        - goheader
      text: "Helm"
    - linters:
        - goheader
      text: "Kubernetes"
    - linters:
        - goheader
      text: "SPDX-License-Identifier"
    - linters:
        - goheader
      text: "Authors"
    - linters:
        - goheader
      text: "Copyright"
    - linters:
        - goheader
      text: "rights reserved"
    - linters:
        - staticcheck
      text: "SA1019: common.ZenTaoOldOSSType is deprecated"
  exclude-dirs:
    - hack/bin
    - testdata$
    - examples$
    - vendor$
    - third_party$
    - internal/static
  exclude-files:
    - "zz_*"
    - ".*test\\.go$"

linters-settings:
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/easysoft/qcadmin)
      - blank
      - dot
      - alias

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  stylecheck:
    # https://staticcheck.io/docs/options#checks
    checks:
      [
        "all",
        "-S1*",
        "-ST1000",
        "-ST1003",
        "-ST1016",
        "-ST1020",
        "-ST1021",
        "-ST1022",
        "-SA5011",
        "-SA1019",
        "-SA2002",
      ]
    # https://staticcheck.io/docs/options#dot_import_whitelist
    dot-import-whitelist:
      - fmt
    # https://staticcheck.io/docs/options#initialisms
    initialisms:
      [
        "ACL",
        "API",
        "ASCII",
        "CPU",
        "CSS",
        "DNS",
        "EOF",
        "GUID",
        "HTML",
        "HTTP",
        "HTTPS",
        "ID",
        "IP",
        "JSON",
        "QPS",
        "RAM",
        "RPC",
        "SLA",
        "SMTP",
        "SQL",
        "SSH",
        "TCP",
        "TLS",
        "TTL",
        "UDP",
        "UI",
        "GID",
        "UID",
        "UUID",
        "URI",
        "URL",
        "UTF8",
        "VM",
        "XML",
        "XMPP",
        "XSRF",
        "XSS",
      ]
    # https://staticcheck.io/docs/options#http_status_code_whitelist
    http-status-code-whitelist: ["200", "400", "404", "500"]

  nakedret:
    # default 30
    max-func-lines: 100

  goheader:
    template-path: .go-header.txt

  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: unused-parameter
        disabled: true

  errcheck:
    check-type-assertions: false
    check-blank: true
    exclude-functions:
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)

  gosmopolitan:
    allow-time-local: true
