# Copyright (c) 2021-2023 北京渠成软件有限公司(Beijing Qucheng Software Co., Ltd. www.qucheng.com) All rights reserved.
# Use of this source code is covered by the following dual licenses:
# (1) Z PUBLIC LICENSE 1.2 (ZPL 1.2)
# (2) Affero General Public License 3.0 (AGPL 3.0)
# license that can be found in the LICENSE file.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qcli-cm
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qcli-cm-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: qcli-cm
  namespace: kube-system
---
apiVersion: batch/v1
kind: Job
metadata:
  name: qcli-cm
  namespace: kube-system
  labels:
    app: qcli-cm
spec:
  backoffLimit: 1
  template:
    metadata:
      name: qcli-cm
      labels:
        app: qcli-cm
    spec:
      serviceAccountName: qcli-cm
      containers:
      - name: qcli-cm
        image: hub.zentao.net/platform/podinstall:2022102713
        imagePullPolicy: Always
        env:
        - name: APP_NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: APP_DOMAIN
          value: demo.corp.cc
        - name: APP_TOKEN
          value: demo-haogs-cn
        - name: APP_HTTP_PORT
          value: "80"
        - name: APP_HTTPS_PORT
          value: "443"
        volumeMounts:
        - name: k3syaml
          mountPath: /qcli/k3syaml
        - name: qcfg
          mountPath: /qcli/root
        - name: qbin
          mountPath: /qcli/qbin
      volumes:
      - name: k3syaml
        hostPath:
          path: /etc/rancher/k3s
      - name: qcfg
        hostPath:
          path: /root
      - name: qbin
        hostPath:
          path: /usr/local/bin
      restartPolicy: Never

