# Copyright (c) 2021-2023 北京渠成软件有限公司(Beijing Qucheng Software Co., Ltd. www.qucheng.com) All rights reserved.
# Use of this source code is covered by the following dual licenses:
# (1) Z PUBLIC LICENSE 1.2 (ZPL 1.2)
# (2) Affero General Public License 3.0 (AGPL 3.0)
# license that can be found in the LICENSE file.

apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: renewtls
  name: renewtls
  namespace: cne-system
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        job-name: renewtls
    spec:
      containers:
      - env:
        - name: DOMAIN
          value: zcz13.haogs.cn
        image: hub.zentao.net/platform/tlsrenew:2022
        imagePullPolicy: Always
        name: renewtls
      restartPolicy: OnFailure
      serviceAccount: qucheng
      serviceAccountName: qucheng
      terminationGracePeriodSeconds: 30
