name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Publish .deb & .rpm to Gemfury
      env:
        FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
      run: |
        curl -F package=@dist/qcadmin*linux_amd64.deb https://{$FURY_TOKEN}@push.fury.io/qucheng/
        curl -F package=@dist/qcadmin*linux_arm64.deb https://{$FURY_TOKEN}@push.fury.io/qucheng/
        curl -F package=@dist/qcadmin*linux_amd64.rpm https://{$FURY_TOKEN}@push.fury.io/qucheng/
        curl -F package=@dist/qcadmin*linux_arm64.rpm https://{$FURY_TOKEN}@push.fury.io/qucheng/
