# Copyright (c) 2021-2023 北京渠成软件有限公司(Beijing Qucheng Software Co., Ltd. www.qucheng.com) All rights reserved.
# Use of this source code is covered by the following dual licenses:
# (1) Z PUBLIC LICENSE 1.2 (ZPL 1.2)
# (2) Affero General Public License 3.0 (AGPL 3.0)
# license that can be found in the LICENSE file.

version: '3.3'
services:
  debian:
    image: takeyamajp/debian-sshd
    container_name: debian
    environment:
      ROOT_PASSWORD: sshutil
    restart: always
    ports:
      - "10022:22"
  centos:
    image: jdeathe/centos-ssh:2.6.1
    container_name: centos
    environment:
      SSH_USER_PASSWORD: sshutil
      SSH_USER: sshutil
      SSH_PASSWORD_AUTHENTICATION: "true"
    restart: always
    ports:
      - "10023:22"
